import React, { useState, useRef, useEffect, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { Pencil, Check, X } from "lucide-react";
import { useMeetingStore } from "../../stores/meetingStore";

/**
 * MeetingTitleEditor - Inline editor for meeting session titles.
 *
 * Features:
 * - Displays the current meeting title (default format: timestamp-based)
 * - Click-to-edit functionality after recording stops
 * - Saves on blur or Enter key press
 * - Cancel editing with Escape key
 * - Disabled during recording (cannot edit while recording)
 *
 * The default title is generated by the backend in timestamp format:
 * "Meeting - January 15, 2025 3:30 PM"
 */
export const MeetingTitleEditor: React.FC = () => {
  const { t } = useTranslation();

  // Connect to meetingStore for state and actions
  const { currentSession, sessionStatus, updateTitle } = useMeetingStore();

  // Local state for editing
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // Determine if editing is allowed (not during recording or processing)
  const canEdit = sessionStatus !== "recording" && sessionStatus !== "processing";

  // Initialize edit value when entering edit mode
  const startEditing = useCallback(() => {
    if (!canEdit || !currentSession) return;
    setEditValue(currentSession.title);
    setIsEditing(true);
  }, [canEdit, currentSession]);

  // Focus input when entering edit mode
  useEffect(() => {
    if (isEditing && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [isEditing]);

  // Cancel editing and revert changes
  const cancelEditing = useCallback(() => {
    setIsEditing(false);
    setEditValue("");
  }, []);

  // Save the new title
  const saveTitle = useCallback(async () => {
    if (!currentSession || isSaving) return;

    const trimmedValue = editValue.trim();

    // If empty or unchanged, just cancel
    if (!trimmedValue || trimmedValue === currentSession.title) {
      cancelEditing();
      return;
    }

    setIsSaving(true);
    try {
      await updateTitle(trimmedValue);
      setIsEditing(false);
      setEditValue("");
    } finally {
      setIsSaving(false);
    }
  }, [currentSession, editValue, isSaving, updateTitle, cancelEditing]);

  // Handle key events in input
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === "Enter") {
        e.preventDefault();
        saveTitle();
      } else if (e.key === "Escape") {
        e.preventDefault();
        cancelEditing();
      }
    },
    [saveTitle, cancelEditing]
  );

  // Handle blur event
  const handleBlur = useCallback(() => {
    // Small delay to allow click on save/cancel buttons
    setTimeout(() => {
      if (isEditing) {
        saveTitle();
      }
    }, 100);
  }, [isEditing, saveTitle]);

  // Handle input change
  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setEditValue(e.target.value);
    },
    []
  );

  // Don't render if no session
  if (!currentSession) {
    return null;
  }

  return (
    <div className="flex items-center gap-2">
      {isEditing ? (
        // Edit mode: show input with save/cancel buttons
        <div className="flex items-center gap-2 flex-1">
          <input
            ref={inputRef}
            type="text"
            value={editValue}
            onChange={handleChange}
            onKeyDown={handleKeyDown}
            onBlur={handleBlur}
            disabled={isSaving}
            className="flex-1 px-2 py-1 text-sm font-semibold bg-mid-gray/10 border border-logo-primary/60 rounded text-primary focus:outline-none focus:border-logo-primary focus:bg-logo-primary/20 transition-all duration-150"
            placeholder={t("meeting.titlePlaceholder", "Enter meeting title...")}
          />
          {/* Save button */}
          <button
            onClick={saveTitle}
            disabled={isSaving}
            className="p-1 rounded hover:bg-green-500/20 text-green-500 transition-colors disabled:opacity-50"
            title={t("common.save", "Save")}
          >
            <Check size={16} />
          </button>
          {/* Cancel button */}
          <button
            onClick={cancelEditing}
            disabled={isSaving}
            className="p-1 rounded hover:bg-red-500/20 text-red-400 transition-colors disabled:opacity-50"
            title={t("common.cancel", "Cancel")}
          >
            <X size={16} />
          </button>
        </div>
      ) : (
        // Display mode: show title with edit button
        <div className="flex items-center gap-2 flex-1 group">
          <span className="text-sm font-medium text-primary truncate">
            {currentSession.title}
          </span>
          {canEdit && (
            <button
              onClick={startEditing}
              className="p-1 rounded opacity-0 group-hover:opacity-100 hover:bg-mid-gray/20 text-mid-gray hover:text-primary transition-all duration-150"
              title={t("meeting.editTitle", "Edit title")}
            >
              <Pencil size={14} />
            </button>
          )}
          {!canEdit && (
            <span className="text-xs text-mid-gray italic">
              {sessionStatus === "recording"
                ? t("meeting.editAfterRecording", "(edit after recording)")
                : ""}
            </span>
          )}
        </div>
      )}
    </div>
  );
};

export default MeetingTitleEditor;
