
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDiarizationEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_diarization_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSonioxApiKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_soniox_api_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeFunasrBaseUrlSetting(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_funasr_base_url_setting", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecommendedFirstModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recommended_first_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFunasrRuntimeConfig(baseUrl: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_funasr_runtime_config", { baseUrl, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFunasrRuntimeStatus() : Promise<Result<FunasrRuntimeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_funasr_runtime_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setupFunasrRuntime() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_funasr_runtime") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFunasrRuntime() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_funasr_runtime") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries() : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts a new meeting session recording.
 * 
 * This command:
 * 1. Validates no active recording is in progress
 * 2. Optionally loads a template with pre-configured settings
 * 3. Creates a new meeting session with UUID and folder
 * 4. Starts audio capture with the specified (or template-based) source
 * 5. Updates session status to Recording
 * 
 * # Arguments
 * * `audio_source` - The audio source configuration (microphone_only, system_only, or mixed)
 * If None and template_id is provided, uses template's audio_source
 * * `template_id` - Optional ID of a meeting template to use for this session
 * 
 * # Returns
 * * `Ok(MeetingSession)` - The newly created and active session
 * * `Err(String)` - If state guard fails, template not found, or recording initialization fails
 */
async startMeetingSession(audioSource: AudioSourceType | null, templateId: string | null, sttEngine: string | null, sonioxApiKey: string | null, funasrBaseUrl: string | null, funasrModel: string | null, title: string | null, participants: string | null, tags: string | null) : Promise<Result<MeetingSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_meeting_session", { audioSource, templateId, sttEngine, sonioxApiKey, funasrBaseUrl, funasrModel, title, participants, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stops the current meeting session recording.
 * 
 * This command:
 * 1. Validates current session is in Recording state
 * 2. Stops audio capture
 * 3. Finalizes WAV file
 * 4. Updates session status to Processing
 * 5. Spawns background transcription task
 * 
 * # Returns
 * * `Ok(String)` - The relative path to the audio file (e.g., "{session-id}/audio.wav")
 * * `Err(String)` - If no recording is active or stopping fails
 */
async stopMeetingSession() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_meeting_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseMeetingSession() : Promise<Result<MeetingSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_meeting_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeMeetingSession() : Promise<Result<MeetingSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_meeting_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the current meeting status.
 * 
 * Returns the status of the currently active session, if any.
 * 
 * # Returns
 * * `Some(MeetingStatus)` - The current session status if a session exists
 * * `None` - If no active session
 */
async getMeetingStatus() : Promise<MeetingStatus | null> {
    return await TAURI_INVOKE("get_meeting_status");
},
/**
 * Gets the current active meeting session.
 * 
 * Returns full details of the currently active session, if any.
 * 
 * # Returns
 * * `Ok(Some(MeetingSession))` - The current session if active
 * * `Ok(None)` - If no active session
 * * `Err(String)` - If database query fails
 */
async getCurrentMeeting() : Promise<Result<MeetingSession | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates the title of a meeting session.
 * 
 * Updates the title in the database. The title can be edited at any time
 * after the session is created.
 * 
 * # Arguments
 * * `session_id` - The unique ID of the session to update
 * * `title` - The new title for the session
 * 
 * # Returns
 * * `Ok(())` - If the title was updated successfully
 * * `Err(String)` - If session not found or database update fails
 */
async updateMeetingTitle(sessionId: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting_title", { sessionId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retries transcription for a failed meeting session, with optional model/language overrides.
 * 
 * # Arguments
 * * `session_id` - The unique ID of the session to retry
 * * `model_id` - Optional model override for this transcription run
 * * `language` - Optional language override for this transcription run
 * 
 * # Returns
 * * `Ok(())` - If retry was initiated successfully
 * * `Err(String)` - If session not found, not in a retryable status, or retry fails
 */
async retryTranscription(sessionId: string, modelId: string | null, language: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_transcription", { sessionId, modelId, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Imports an external audio file as a new meeting session and starts transcription.
 * 
 * Supported formats: .wav, .mp3, .m4a, .flac, .ogg
 * Non-WAV files are copied as-is with a warning; WAV files are copied directly.
 * The audio must be (or become) 16kHz mono 16-bit PCM for transcription.
 */
async importMeetingAudio(filePath: string, title: string | null) : Promise<Result<MeetingSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_meeting_audio", { filePath, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the transcript text content for a completed meeting session.
 * 
 * Reads the transcript file from disk and returns its content.
 * 
 * # Arguments
 * * `session_id` - The unique ID of the session to get transcript for
 * 
 * # Returns
 * * `Ok(Some(String))` - The transcript text if available
 * * `Ok(None)` - If no transcript exists for this session
 * * `Err(String)` - If session not found or file read fails
 */
async getMeetingTranscript(sessionId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_transcript", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all meeting sessions.
 * 
 * Returns all meeting sessions from the database, ordered by creation time
 * (newest first).
 * 
 * # Returns
 * * `Ok(Vec<MeetingSession>)` - All meeting sessions
 * * `Err(String)` - If database query fails
 */
async listMeetingSessions() : Promise<Result<MeetingSession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meeting_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the path to the meetings directory.
 * 
 * # Returns
 * * `Ok(String)` - The absolute path to the meetings directory
 * * `Err(String)` - If getting the path fails
 */
async getMeetingsDirectory() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meetings_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a meeting session and its associated files.
 * 
 * This command:
 * 1. Validates the session exists
 * 2. Deletes the session folder (audio, transcript files)
 * 3. Removes the session from the database
 * 
 * # Arguments
 * * `session_id` - The unique ID of the session to delete
 * 
 * # Returns
 * * `Ok(())` - If the session was deleted successfully
 * * `Err(String)` - If session not found or deletion fails
 */
async deleteMeetingSession(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllMeetingSessions() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_meeting_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generates an AI summary for a meeting session.
 * 
 * This command:
 * 1. Validates the session exists and has a transcript
 * 2. Reads the transcript content
 * 3. Sends it to the configured LLM provider for summarization
 * 4. Saves the summary to a markdown file
 * 5. Updates the session with the summary path
 * 
 * # Arguments
 * * `session_id` - The unique ID of the session to summarize
 * 
 * # Returns
 * * `Ok(String)` - The generated summary text
 * * `Err(String)` - If session not found, no transcript, or LLM call fails
 */
async generateMeetingSummary(sessionId: string, outputLanguage: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_meeting_summary", { sessionId, outputLanguage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the summary text content for a meeting session.
 * 
 * Reads the summary file from disk and returns its content.
 * 
 * # Arguments
 * * `session_id` - The unique ID of the session to get summary for
 * 
 * # Returns
 * * `Ok(Some(String))` - The summary text if available
 * * `Ok(None)` - If no summary exists for this session
 * * `Err(String)` - If session not found or file read fails
 */
async getMeetingSummary(sessionId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_summary", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves an edited summary for a meeting session.
 * 
 * Writes the new summary text to `summary.md` in the session directory and
 * updates the `summary_path` column in the database.
 */
async updateMeetingSummary(sessionId: string, summary: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting_summary", { sessionId, summary }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Extracts structured insights (key points, action items, participants) from
 * a meeting transcript using the configured LLM, persists them (replacing any
 * previous AI-extracted data for the session), and returns the stored result.
 */
async extractMeetingInsights(sessionId: string, outputLanguage: string | null) : Promise<Result<MeetingInsights, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_meeting_insights", { sessionId, outputLanguage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a timestamped note to an existing meeting session.
 * 
 * The timestamp is given in seconds from the start of the recording and is
 * stored as-is. Pass `0` for notes captured outside a recording.
 */
async addMeetingNote(sessionId: string, timestampSeconds: number, content: string) : Promise<Result<MeetingNote, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_meeting_note", { sessionId, timestampSeconds, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists every note attached to a meeting session, oldest first.
 */
async listMeetingNotes(sessionId: string) : Promise<Result<MeetingNote[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meeting_notes", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a single meeting note by id.
 */
async deleteMeetingNote(noteId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting_note", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMeetingActionItem(sessionId: string, task: string, assignee: string | null, dueDate: string | null, status: ActionItemStatus | null) : Promise<Result<ActionItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_meeting_action_item", { sessionId, task, assignee, dueDate, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMeetingActionItems(sessionId: string) : Promise<Result<ActionItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meeting_action_items", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMeetingActionItem(item: ActionItem) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting_action_item", { item }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMeetingActionItem(itemId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting_action_item", { itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMeetingKeyPoint(sessionId: string, category: string | null, content: string) : Promise<Result<KeyPoint, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_meeting_key_point", { sessionId, category, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMeetingKeyPoints(sessionId: string) : Promise<Result<KeyPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meeting_key_points", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMeetingParticipant(sessionId: string, name: string, role: string | null) : Promise<Result<Participant, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_meeting_participant", { sessionId, name, role }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMeetingParticipants(sessionId: string) : Promise<Result<Participant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meeting_participants", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMeetingParticipant(participant: Participant) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting_participant", { participant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMeetingParticipant(participantId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting_participant", { participantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sets the active speaker for the current meeting session.
 * All transcript segments emitted after this call will be attributed to
 * `participant_id` until the active speaker is changed again.
 */
async setActiveSpeaker(participantId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_speaker", { participantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all transcript segments for a meeting, ordered by sequence.
 * Used by MeetingDetailView and MeetingTranscriptDisplay to render
 * speaker-attributed transcript after recording is complete.
 */
async getMeetingTranscriptSegments(sessionId: string) : Promise<Result<TranscriptSegment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_transcript_segments", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMeetingTag(sessionId: string, label: string, color: string | null) : Promise<Result<Tag, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_meeting_tag", { sessionId, label, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMeetingTags(sessionId: string) : Promise<Result<Tag[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meeting_tags", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMeetingTag(tagId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting_tag", { tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAllMeetingTagLabels() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_all_meeting_tag_labels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMeetingTemplates() : Promise<Result<MeetingTemplate[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meeting_templates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createMeetingTemplate(name: string, icon: string, titleTemplate: string, audioSource: string, promptId: string | null, summaryPromptTemplate: string | null, sttEngine: string | null) : Promise<Result<MeetingTemplate, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_meeting_template", { name, icon, titleTemplate, audioSource, promptId, summaryPromptTemplate, sttEngine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMeetingTemplate(id: string, name: string | null, icon: string | null, titleTemplate: string | null, audioSource: string | null, promptId: string | null, summaryPromptTemplate: string | null, sttEngine: string | null) : Promise<Result<MeetingTemplate, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting_template", { id, name, icon, titleTemplate, audioSource, promptId, summaryPromptTemplate, sttEngine }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMeetingTemplate(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting_template", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Translates `text` from `source` language to `target` language.
 * 
 * `source` may be "auto" to let Google detect the language. Language codes
 * follow ISO 639-1 (e.g. "en", "vi", "ja", "zh-CN").
 */
async translateText(text: string, source: string, target: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("translate_text", { text, source, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Synthesize text using Edge TTS. Returns base64-encoded MP3 audio.
 * `voice` example: "vi-VN-HoaiMyNeural", "en-US-JennyNeural"
 * `rate` is a percentage offset, e.g. 20 → "+20%", -10 → "-10%"
 */
async edgeTtsSpeak(text: string, voice: string, rate: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edge_tts_speak", { text, voice, rate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkScreenRecordingPermission() : Promise<boolean> {
    return await TAURI_INVOKE("check_screen_recording_permission");
},
async requestScreenRecordingPermissionCmd() : Promise<boolean> {
    return await TAURI_INVOKE("request_screen_recording_permission_cmd");
},
/**
 * Opens (or focuses) the ChatGPT login webview window. The user signs in
 * inside that window; once a session is established the injected script
 * captures the access token and calls back into `complete_chatgpt_login`.
 */
async openChatgptLogin() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_chatgpt_login") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Called by the injected script when it has extracted an access token from
 * the chatgpt.com session. Emits an app-level event so the settings UI can
 * persist the token, then closes the login window.
 */
async completeChatgptLogin(accessToken: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_chatgpt_login", { accessToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sonioxStart(config: SonioxConfig, onEvent: __TAURI_CHANNEL__<SonioxEvent>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("soniox_start", { config, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sonioxSendAudio(sessionId: number, pcm: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("soniox_send_audio", { sessionId, pcm }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sonioxStop(sessionId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("soniox_stop", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if the Mac is a laptop by detecting battery presence
 * 
 * This uses pmset to check for battery information.
 * Returns true if a battery is detected (laptop), false otherwise (desktop)
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check the full status of Ollama: installed? running? which models?
 */
async checkOllamaStatus() : Promise<OllamaStatusResponse> {
    return await TAURI_INVOKE("check_ollama_status");
},
/**
 * Start the Ollama server and wait for it to be ready.
 * Returns true if server started successfully.
 */
async startOllama() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_ollama") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pull (download) a model with progress events emitted to frontend.
 * This is a long-running operation that streams progress updates.
 */
async pullOllamaModel(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_ollama_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the install URL for Ollama based on the current platform.
 */
async getOllamaInstallUrl() : Promise<string> {
    return await TAURI_INVOKE("get_ollama_install_url");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A task extracted from (or added to) a meeting.
 */
export type ActionItem = { id: string; session_id: string; task: string; assignee: string | null; 
/**
 * Free-form due date string (e.g. "Cuối tháng", "Tuần này", "2025-06-01").
 * Kept as text so AI-extracted relative dates are preserved.
 */
due_date: string | null; status: ActionItemStatus; sort_order: number; created_at: number }
/**
 * Status of an action item.
 */
export type ActionItemStatus = "todo" | "in_progress" | "done" | "blocked"
export type AppSettings = { bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; selected_model?: string; always_on_microphone?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: Partial<{ [key in string]: string }>; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; meeting_templates?: MeetingTemplate[]; auto_save?: boolean; auto_transcribe?: boolean; auto_summary?: boolean; notify_completed?: boolean; notify_failed?: boolean; notify_app_updates?: boolean; soniox_api_key?: string | null; 
/**
 * "whisper" | "soniox" | "funasr". Defaults to "whisper".
 */
meeting_stt_engine?: string; funasr_base_url?: string; funasr_model?: string; 
/**
 * Enable speaker diarization for meeting transcripts (requires diarization models).
 */
diarization_enabled?: boolean }
export type AudioDevice = { index: string; name: string; is_default: boolean }
/**
 * Audio source configuration for meeting recording
 */
export type AudioSourceType = 
/**
 * Only capture microphone input (default)
 */
"microphone_only" | 
/**
 * Only capture system audio (YouTube, Zoom, etc.) - macOS 13.0+ only
 */
"system_only" | 
/**
 * Capture both microphone and system audio mixed together - macOS 13.0+ only
 */
"mixed"
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = "TranscribeCpp" | "Parakeet" | "Diarization"
export type FunasrRuntimeStatus = { installed: boolean; server_running: boolean; download_percentage: number | null; base_url: string; model: string; runtime_dir: string; log_path: string; message: string }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null }
/**
 * A discussion bullet/point. `category` groups multiple points under a heading.
 */
export type KeyPoint = { id: string; session_id: string; category: string | null; content: string; sort_order: number; created_at: number }
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * Bundle of AI-extracted structured data for a meeting.
 * Used as the return type of `extract_meeting_insights`.
 */
export type MeetingInsights = { key_points: KeyPoint[]; action_items: ActionItem[]; participants: Participant[]; tags: Tag[] }
/**
 * A short, timestamped note attached to a meeting session.
 * 
 * Notes are captured during a recording (via the "Add Note" button) or
 * after the fact in the Notes tab. They are stored in their own table
 * keyed by `session_id` with `ON DELETE CASCADE` so removing a session
 * also removes its notes.
 */
export type MeetingNote = { 
/**
 * Unique identifier (UUID).
 */
id: string; 
/**
 * Session this note belongs to.
 */
session_id: string; 
/**
 * Offset from the start of the recording, in seconds.
 * May be `0` for notes added before recording starts or after it stops.
 */
timestamp_seconds: number; 
/**
 * Free-form note content (plain text, may contain newlines).
 */
content: string; 
/**
 * Optional author label. Reserved for future multi-user support;
 * currently always `None` from the UI.
 */
author: string | null; 
/**
 * Unix timestamp (seconds) when the note was created.
 */
created_at: number }
/**
 * Represents a meeting session with its metadata and file references.
 * 
 * Each meeting session has a unique ID and is stored in a dedicated folder
 * under the app's data directory: `{app_data}/meetings/{session-id}/`
 */
export type MeetingSession = { 
/**
 * Unique identifier for the session (UUID format)
 */
id: string; 
/**
 * User-editable title, defaults to timestamp format like
 * "Meeting - January 15, 2025 3:30 PM"
 */
title: string; 
/**
 * Unix timestamp (seconds) when the meeting was created/started
 */
created_at: number; 
/**
 * Duration of the recording in seconds (set after recording stops)
 */
duration: number | null; 
/**
 * Current status of the meeting session
 */
status: MeetingStatus; 
/**
 * Relative path to the audio file within the meetings directory
 * e.g., "{session-id}/audio.wav"
 */
audio_path: string | null; 
/**
 * Relative path to the transcript file within the meetings directory
 * e.g., "{session-id}/transcript.txt"
 */
transcript_path: string | null; 
/**
 * Error message if the meeting failed
 */
error_message: string | null; 
/**
 * Audio source configuration for this meeting
 */
audio_source: AudioSourceType; 
/**
 * Relative path to the AI-generated summary file within the meetings directory
 * e.g., "{session-id}/summary.md"
 */
summary_path: string | null; 
/**
 * Template ID if this meeting was created from a template
 */
template_id?: string | null; stt_engine?: string; funasr_base_url?: string | null; funasr_model?: string | null; transcription_language?: string | null }
/**
 * Represents the lifecycle status of a meeting session.
 * 
 * The state machine follows this flow:
 * - Idle -> Recording (start meeting)
 * - Recording -> Processing (stop meeting, begin transcription)
 * - Recording -> Interrupted (app closed during recording)
 * - Processing -> Completed (transcription success)
 * - Processing -> Failed (transcription failure)
 * - Failed -> Processing (retry transcription)
 * - Interrupted -> Processing (resume transcription on next launch)
 */
export type MeetingStatus = 
/**
 * No active meeting session
 */
"idle" | 
/**
 * Meeting is currently being recorded
 */
"recording" | 
/**
 * Recording stopped, transcription in progress
 */
"processing" | 
/**
 * Meeting completed successfully with transcript
 */
"completed" | 
/**
 * Meeting failed (e.g., transcription error), audio preserved
 */
"failed" | 
/**
 * Meeting was interrupted (app closed during recording), audio preserved
 */
"interrupted"
export type MeetingTemplate = { id: string; name: string; icon: string; title_template: string; audio_source: string; prompt_id: string | null; summary_prompt_template?: string | null; 
/**
 * STT engine override for this template: "whisper" | "soniox" | "funasr". Empty = use global setting.
 */
stt_engine?: string | null; created_at: number; updated_at: number }
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supported_languages: string[]; is_recommended: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_5"
/**
 * Information about a locally available Ollama model
 */
export type OllamaModelInfo = { name: string; size: number; modified_at: string }
/**
 * Status of the Ollama service
 */
export type OllamaStatus = 
/**
 * Ollama is not installed on this system
 */
"not_installed" | 
/**
 * Ollama is installed but the server is not running
 */
"installed" | 
/**
 * Ollama server is running and ready
 */
"running"
/**
 * Combined status response for the frontend
 */
export type OllamaStatusResponse = { status: OllamaStatus; models: OllamaModelInfo[]; version: string | null; binary_path: string | null }
export type OverlayPosition = "none" | "top" | "bottom"
/**
 * A person attached to a meeting (extracted from transcript or added manually).
 */
export type Participant = { id: string; session_id: string; name: string; 
/**
 * Free-form role/team label, e.g. "Marketing", "Sales".
 */
role: string | null; sort_order: number; created_at: number; 
/**
 * Index into the SPEAKER_COLORS palette (0-7). -1 = unassigned.
 */
color_index?: number }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v"
export type PostProcessProvider = { id: string; label: string; base_url: string; 
/**
 * Whether this provider requires an API key. Local providers (Ollama, LM Studio) don't.
 */
requires_api_key?: boolean; 
/**
 * Default model to use if none is configured (e.g., "llama3.2" for Ollama)
 */
default_model?: string | null }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SonioxConfig = { api_key: string; 
/**
 * Source language hint, e.g. "vi", "en", "auto"
 */
source_language: string; 
/**
 * Target language for translation, e.g. "en". Empty = no translation.
 */
target_language: string | null; 
/**
 * Session ID for event correlation
 */
session_id: string }
export type SonioxEvent = { type: "status"; state: string } | { type: "transcript"; session_id: string; text: string; chunk_text: string; is_final: boolean; speaker: string | null } | { type: "error"; message: string } | { type: "closed"; reason: string }
export type SoundTheme = "marimba" | "pop" | "custom"
export type TAURI_CHANNEL<TSend> = null
/**
 * A tag for filtering/organizing meetings.
 */
export type Tag = { id: string; session_id: string; label: string; 
/**
 * Optional Tailwind-compatible color token (e.g. "blue", "amber").
 */
color: string | null; created_at: number }
/**
 * A structured transcript segment with optional speaker attribution.
 * Stored in the `transcript_segments` table.
 */
export type TranscriptSegment = { id: string; meeting_id: string; 
/**
 * Start time in milliseconds from the beginning of the recording.
 */
start_ms: number; 
/**
 * End time in milliseconds from the beginning of the recording.
 */
end_ms: number; 
/**
 * The transcribed text for this segment.
 */
text: string; 
/**
 * Optional participant ID of the speaker. None = unassigned.
 */
speaker_id: string | null; 
/**
 * Monotonically increasing sequence number for ordering.
 */
sequence: number; 
/**
 * Unix timestamp (ms) when the segment was created.
 */
created_at: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as __TAURI_CHANNEL__,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
